packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@biomejs/biome': ^2.1.2
  '@turbo/gen': ^2.5.5
  '@types/node': ^22.15.30
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.1
  eslint: ^9.31.0
  next: ^15.3.0
  prettier: ^3.6.2
  react: ^19.1.0
  react-dom: ^19.1.0
  turbo: ^2.5.5
  typescript: ^5.8.3

onlyBuiltDependencies:
  - core-js-pure
