packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@biomejs/biome': ^2.1.2
  '@next/bundle-analyzer': ^15.4.1
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@tailwindcss/cli': ^4.1.11
  '@tailwindcss/postcss': ^4.1.5
  '@tailwindcss/typography': ^0.5.16
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@turbo/gen': ^2.5.5
  '@types/jest': ^30.0.0
  '@types/node': ^22.15.30
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.1
  jest: ^30.0.4
  jest-environment-jsdom: ^30.0.4
  next: ^15.3.0
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwind-merge: ^2.6.0
  tailwindcss: ^4.1.11
  tailwindcss-animate: ^1.0.7
  ts-jest: ^29.4.0
  ts-node: ^10.9.2
  turbo: ^2.5.5
  tw-animate-css: ^1.3.5
  typescript: ^5.8.3
  zod: ^4.0.5

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js-pure
